"""
VINIV Auto Report — Scheduled script
Runs automatically on Saturday 11:30 PM (London time).
Generates report from TISSL, saves to Firestore, sends email to self.
"""

import time
import json
import smtplib
import os
from datetime import datetime, timedelta
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.edge.service import Service
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.microsoft import EdgeChromiumDriverManager

# Firebase Admin SDK
import firebase_admin
from firebase_admin import credentials, firestore

# ============================================================
# CONFIGURATION
# ============================================================
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ACCOUNTS_FILE = os.path.join(SCRIPT_DIR, "accounts.json")
FIREBASE_KEY_FILE = os.path.join(SCRIPT_DIR, "firebase-service-key.json")

GLASS_PRICE = 27.00


def load_accounts():
    with open(ACCOUNTS_FILE, "r") as f:
        return json.load(f)


# ============================================================
# FIREBASE
# ============================================================
def init_firebase():
    if not firebase_admin._apps:
        cred = credentials.Certificate(FIREBASE_KEY_FILE)
        firebase_admin.initialize_app(cred)
    return firestore.client()


def save_to_firestore(db_client, data, account_name):
    db_client.collection("viniv_reports").add({
        "weekStart": data["weekStart"],
        "weekEnd": data["weekEnd"],
        "totalGlass": data["totalGlass"],
        "totalPairing": data["totalPairing"],
        "totalAll": data["totalAll"],
        "entries": data["entries"],
        "accountName": account_name,
        "emailSent": False,
        "createdAt": firestore.SERVER_TIMESTAMP,
        "autoGenerated": True
    })


# ============================================================
# SELENIUM FUNCTIONS
# ============================================================
def create_driver():
    options = webdriver.EdgeOptions()
    options.add_argument("--headless=new")
    options.add_argument("--disable-gpu")
    options.add_argument("--no-sandbox")
    options.add_argument("--window-size=1920,1080")
    service = Service(EdgeChromiumDriverManager().install())
    return webdriver.Edge(service=service, options=options)


def login(driver, wait, username, password):
    driver.get("https://hub.tissl.com")
    time.sleep(3)
    username_field = wait.until(EC.presence_of_element_located(
        (By.CSS_SELECTOR, "input[placeholder='Username'], input[name='username'], input[type='text']")
    ))
    username_field.clear()
    username_field.send_keys(username)
    password_field = driver.find_element(By.CSS_SELECTOR, "input[placeholder='Password'], input[name='password'], input[type='password']")
    password_field.clear()
    password_field.send_keys(password)
    login_btn = driver.find_element(By.XPATH, "//button[contains(text(), 'Log In')] | //button[contains(text(), 'Login')]")
    login_btn.click()
    time.sleep(5)


def accept_cookies(driver):
    try:
        cookie_btn = driver.find_element(By.CSS_SELECTOR, "button.cookie-consent-accept-button")
        cookie_btn.click()
        time.sleep(1)
    except Exception:
        pass


def navigate_to_report(driver, wait):
    driver.get("https://hub.tissl.com/report-centre/extended-sales-mix")
    time.sleep(5)


def set_date_range(driver, wait):
    date_input = wait.until(EC.presence_of_element_located(
        (By.CSS_SELECTOR, "input[name='dpFromDate']")
    ))
    driver.execute_script("arguments[0].click();", date_input)
    time.sleep(2)

    # Use "This Week" since we run on Saturday night (end of the week)
    this_week_btn = wait.until(EC.presence_of_element_located(
        (By.XPATH, "//button[contains(text(), 'This Week')]")
    ))
    driver.execute_script("arguments[0].scrollIntoView(true);", this_week_btn)
    time.sleep(0.5)
    driver.execute_script("arguments[0].click();", this_week_btn)
    time.sleep(1)

    apply_btn = wait.until(EC.presence_of_element_located(
        (By.XPATH, "//button[contains(text(), 'Apply')]")
    ))
    driver.execute_script("arguments[0].scrollIntoView(true);", apply_btn)
    time.sleep(0.5)
    driver.execute_script("arguments[0].click();", apply_btn)
    time.sleep(2)


def set_category_wine(driver, wait):
    cat_select = wait.until(EC.presence_of_element_located(
        (By.CSS_SELECTOR, "select[formcontrolname='rootCategory']")
    ))
    options = cat_select.find_elements(By.TAG_NAME, "option")
    for option in options:
        if "WINE" in option.text:
            option.click()
            break
    time.sleep(1)


def set_order_type(driver, wait):
    multiselect_btn = wait.until(EC.presence_of_element_located(
        (By.CSS_SELECTOR, "angular2-multiselect .c-btn")
    ))
    driver.execute_script("arguments[0].click();", multiselect_btn)
    time.sleep(2)

    try:
        restaurant_label = driver.find_element(
            By.XPATH, "//angular2-multiselect//ul[contains(@class,'lazyContainer')]//li//label[normalize-space(text())='Restaurant']"
        )
        driver.execute_script("arguments[0].click();", restaurant_label)
        time.sleep(1)
    except Exception:
        pass

    dropdown_list = driver.find_elements(By.CSS_SELECTOR, "angular2-multiselect .dropdown-list:not([hidden])")
    if not dropdown_list:
        driver.execute_script("arguments[0].click();", multiselect_btn)
        time.sleep(2)

    try:
        kitchen_label = driver.find_element(
            By.XPATH, "//angular2-multiselect//ul[contains(@class,'lazyContainer')]//li//label[normalize-space(text())='Kitchen Table']"
        )
        driver.execute_script("arguments[0].click();", kitchen_label)
        time.sleep(1)
    except Exception:
        pass

    driver.find_element(By.CSS_SELECTOR, "body").click()
    time.sleep(1)


def click_view(driver, wait):
    view_btn = wait.until(EC.presence_of_element_located(
        (By.CSS_SELECTOR, "button.btn-primary.btn-sm")
    ))
    driver.execute_script("arguments[0].click();", view_btn)
    time.sleep(8)


def search_and_extract(driver, wait):
    search_box = wait.until(EC.presence_of_element_located(
        (By.CSS_SELECTOR, "input[type='search'], .dataTables_filter input")
    ))
    search_box.clear()
    search_box.send_keys("The Restaurant")
    time.sleep(3)

    rows = driver.find_elements(By.CSS_SELECTOR, "table.table tbody tr")
    results = []
    for row in rows:
        cells = row.find_elements(By.TAG_NAME, "td")
        if len(cells) >= 9:
            try:
                date = cells[0].text.strip()
                session = cells[1].text.strip()
                order_type = cells[2].text.strip()
                product_name = cells[3].text.strip()
                total_sold = int(cells[7].text.strip())
                selling_price = float(cells[8].text.strip())
                sale_type = "By the Glass" if selling_price <= GLASS_PRICE else "Pairing"
                results.append({
                    "date": date,
                    "session": session,
                    "orderType": order_type,
                    "product": product_name,
                    "qty": total_sold,
                    "price": selling_price,
                    "type": sale_type
                })
            except (ValueError, IndexError):
                continue
    return results


# ============================================================
# EMAIL
# ============================================================
def send_notification(config, data):
    """Send the report to yourself as notification."""
    email_config = config["email"]
    
    body = f"Viniv Auto Report generated at {datetime.now().strftime('%d/%m/%Y %H:%M')}\n\n"
    body += f"Week: {data['weekStart']} - {data['weekEnd']}\n"
    body += f"By the Glass: {data['totalGlass']}\n"
    body += f"Pairings: {data['totalPairing']}\n"
    body += f"Total: {data['totalAll']}\n\n"
    body += "Report saved to Firestore. Open the Petrus site to review and send to Giuseppe."

    msg = MIMEMultipart()
    msg["From"] = email_config["from"]
    msg["To"] = email_config["to"]
    msg["Subject"] = f"[Auto] Viniv Report Ready ({data['weekStart']} - {data['weekEnd']})"
    msg.attach(MIMEText(body, "plain"))

    with smtplib.SMTP("smtp.gmail.com", 587) as server:
        server.starttls()
        server.login(email_config["from"], email_config["appPassword"])
        server.sendmail(email_config["from"], email_config["to"], msg.as_string())


# ============================================================
# MAIN
# ============================================================
def main():
    print(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}] Starting Viniv Auto Report...")
    
    config = load_accounts()
    account = config["accounts"][0]  # Use first account
    
    driver = None
    try:
        # Init Firebase
        db_client = init_firebase()
        
        # Run Selenium
        driver = create_driver()
        wait = WebDriverWait(driver, 20)
        
        print("  Logging in...")
        login(driver, wait, account["username"], account["password"])
        accept_cookies(driver)
        
        print("  Navigating to report...")
        navigate_to_report(driver, wait)
        
        print("  Setting filters...")
        set_date_range(driver, wait)
        set_category_wine(driver, wait)
        set_order_type(driver, wait)
        
        print("  Generating report...")
        click_view(driver, wait)
        results = search_and_extract(driver, wait)
        
        if not results:
            print("  ⚠ No data found this week.")
            return
        
        # Calculate totals
        total_glass = sum(r["qty"] for r in results if r["type"] == "By the Glass")
        total_pairing = sum(r["qty"] for r in results if r["type"] == "Pairing")
        
        today = datetime.now()
        # This week: Monday to Saturday
        days_since_monday = today.weekday()
        monday = today - timedelta(days=days_since_monday)
        saturday = monday + timedelta(days=5)
        
        data = {
            "weekStart": monday.strftime("%d/%m/%Y"),
            "weekEnd": saturday.strftime("%d/%m/%Y"),
            "totalGlass": total_glass,
            "totalPairing": total_pairing,
            "totalAll": total_glass + total_pairing,
            "entries": results
        }
        
        print(f"  Found {len(results)} entries. Total: {data['totalAll']}")
        
        # Save to Firestore
        print("  Saving to Firestore...")
        save_to_firestore(db_client, data, account["name"])
        
        # Send notification email
        print("  Sending notification...")
        send_notification(config, data)
        
        print("  ✓ Done! Report ready for review on petrus-site.")
        
    except Exception as e:
        print(f"  ✗ Error: {e}")
    finally:
        if driver:
            driver.quit()


if __name__ == "__main__":
    main()
